ALTER TABLE projects
    ADD COLUMN actual_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00;
ALTER TABLE projects
    ADD COLUMN progress_percent INT NOT NULL DEFAULT 0;
ALTER TABLE projects
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PLANNING';

ALTER TABLE wbs
    ADD COLUMN level_no INT NOT NULL DEFAULT 1;
ALTER TABLE wbs
    ADD COLUMN progress_percent INT NOT NULL DEFAULT 0;
ALTER TABLE wbs
    ADD COLUMN budget_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00;
ALTER TABLE wbs
    ADD COLUMN actual_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00;

ALTER TABLE activities
    ADD COLUMN planned_start DATE NOT NULL DEFAULT '2026-01-01';
ALTER TABLE activities
    ADD COLUMN planned_end DATE NOT NULL DEFAULT '2026-01-01';
ALTER TABLE activities
    ADD COLUMN duration_days INT NOT NULL DEFAULT 0;
ALTER TABLE activities
    ADD COLUMN progress_percent INT NOT NULL DEFAULT 0;
ALTER TABLE activities
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE activities
    ADD COLUMN responsible_user VARCHAR(255) NOT NULL DEFAULT 'Unassigned';

ALTER TABLE risks
    ADD COLUMN category VARCHAR(100) NOT NULL DEFAULT 'General';
ALTER TABLE risks
    ADD COLUMN owner VARCHAR(255) NOT NULL DEFAULT 'Unassigned';
ALTER TABLE risks
    ADD COLUMN probability INT NOT NULL DEFAULT 1;
ALTER TABLE risks
    ADD COLUMN impact INT NOT NULL DEFAULT 1;
ALTER TABLE risks
    ADD COLUMN severity INT NOT NULL DEFAULT 1;
ALTER TABLE risks
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'OPEN';
ALTER TABLE risks
    ADD COLUMN target_date DATE NOT NULL DEFAULT '2026-01-01';
