import type {
  ActivityItem,
  DashboardMetric,
  MaterialRequestItem,
  ProjectSummary,
  ReportSnapshot,
  RiskItem,
  MilestoneItem,
  WbsNode,
} from "@/lib/types";

export const dashboardMetrics: DashboardMetric[] = [
  { label: "Active Projects", value: "12", change: "+2 this quarter", tone: "success" },
  { label: "Budget vs Actual", value: "91.4%", change: "Healthy burn rate", tone: "success" },
  { label: "Delayed Milestones", value: "07", change: "2 need escalation", tone: "warning" },
  { label: "Open Critical Risks", value: "04", change: "1 newly raised", tone: "danger" },
];

export const projectSummaries: ProjectSummary[] = [
  {
    id: "p1",
    code: "PRJ-2401",
    name: "Metro Utility Corridor",
    client: "City Infrastructure Board",
    manager: "Aarav Menon",
    status: "Active",
    progress: 68,
    budget: 12600000,
    actual: 11180000,
    startDate: "2026-01-06",
    endDate: "2026-11-30",
    location: "Bengaluru",
  },
  {
    id: "p2",
    code: "PRJ-2408",
    name: "North Hub Expansion",
    client: "Mercury Logistics",
    manager: "Neha Iyer",
    status: "At Risk",
    progress: 43,
    budget: 8900000,
    actual: 5210000,
    startDate: "2026-02-01",
    endDate: "2026-10-15",
    location: "Hyderabad",
  },
  {
    id: "p3",
    code: "PRJ-2412",
    name: "Solar Assembly Line",
    client: "Axis Renewables",
    manager: "Rohan Jain",
    status: "Planning",
    progress: 18,
    budget: 14300000,
    actual: 1760000,
    startDate: "2026-03-14",
    endDate: "2027-01-20",
    location: "Chennai",
  },
];

export const wbsNodes: WbsNode[] = [
  { id: "w1", code: "1.0", name: "Site Establishment", level: 1, owner: "Planning", progress: 80, budget: 900000, actual: 760000 },
  { id: "w2", code: "2.0", name: "Underground Works", level: 1, owner: "Execution", progress: 61, budget: 3200000, actual: 2940000 },
  { id: "w3", code: "2.1", name: "Trenching & Protection", level: 2, owner: "Civil Team", progress: 55, budget: 1860000, actual: 1745000 },
  { id: "w4", code: "3.0", name: "MEP Integration", level: 1, owner: "MEP Team", progress: 42, budget: 4100000, actual: 2980000 },
];

export const activities: ActivityItem[] = [
  {
    id: "a1",
    projectId: "p1",
    wbsId: "w3",
    activityCode: "ACT-101",
    activityName: "Excavation Zone A",
    wbsCode: "2.1",
    plannedStart: "2026-04-08",
    plannedEnd: "2026-04-28",
    durationDays: 20,
    progressPercent: 72,
    status: "In Progress",
    responsibleUser: "Karthik R",
  },
  {
    id: "a2",
    projectId: "p2",
    wbsId: "w4",
    activityCode: "ACT-114",
    activityName: "Cable Tray Installation",
    wbsCode: "3.0",
    plannedStart: "2026-04-15",
    plannedEnd: "2026-05-06",
    durationDays: 21,
    progressPercent: 35,
    status: "Delayed",
    responsibleUser: "Nitya V",
  },
  {
    id: "a3",
    projectId: "p3",
    wbsId: "w4",
    activityCode: "ACT-126",
    activityName: "Testing & Commissioning",
    wbsCode: "3.0",
    plannedStart: "2026-05-10",
    plannedEnd: "2026-05-20",
    durationDays: 10,
    progressPercent: 0,
    status: "Not Started",
    responsibleUser: "Harish P",
  },
];

export const risks: RiskItem[] = [
  {
    id: "r1",
    projectId: "1",
    activityId: "1",
    riskNo: "RISK-001",
    title: "Delayed authority approval for road cutting",
    category: "Regulatory",
    owner: "Aarav Menon",
    probability: 4,
    impact: 5,
    severity: 20,
    status: "UNDER_REVIEW",
    targetDate: "2026-04-26",
  },
  {
    id: "r2",
    projectId: "2",
    activityId: "4",
    riskNo: "RISK-009",
    title: "Imported panel delivery slips by two weeks",
    category: "Procurement",
    owner: "Neha Iyer",
    probability: 3,
    impact: 5,
    severity: 15,
    status: "MITIGATION_IN_PROGRESS",
    targetDate: "2026-05-02",
  },
  {
    id: "r3",
    projectId: "1",
    activityId: "1",
    riskNo: "RISK-014",
    title: "Heavy rainfall impact on trench stability",
    category: "Execution",
    owner: "Karthik R",
    probability: 4,
    impact: 4,
    severity: 16,
    status: "OPEN",
    targetDate: "2026-04-24",
  },
];

export const milestones: MilestoneItem[] = [
  {
    id: "m1",
    projectId: "p1",
    wbsId: "w1",
    milestoneCode: "MS-001",
    milestoneName: "Site handover complete",
    plannedDate: "2026-02-05",
    actualDate: "2026-02-03",
    status: "COMPLETED",
    wbsCode: "1.0",
  },
  {
    id: "m2",
    projectId: "p1",
    wbsId: "w3",
    milestoneCode: "MS-002",
    milestoneName: "Trenching package released",
    plannedDate: "2026-04-30",
    actualDate: null,
    status: "IN_PROGRESS",
    wbsCode: "2.1",
  },
  {
    id: "m3",
    projectId: "p2",
    wbsId: "w1",
    milestoneCode: "MS-003",
    milestoneName: "Dock slab approval",
    plannedDate: "2026-05-10",
    actualDate: null,
    status: "AT_RISK",
    wbsCode: "1.0",
  },
];

export const materialRequests: MaterialRequestItem[] = [
  {
    id: "mr1",
    requestNo: "MR-24018",
    projectId: "1",
    project: "Metro Utility Corridor",
    activityId: "2",
    activity: "Cable Tray Installation",
    requestedBy: "Nitya V",
    status: "APPROVED",
    requestedQty: 820,
    approvedQty: 800,
    pendingQty: 240,
  },
  {
    id: "mr2",
    requestNo: "MR-24021",
    projectId: "2",
    project: "North Hub Expansion",
    activityId: "4",
    activity: "Dock Reinforcement",
    requestedBy: "Sanjay K",
    status: "PARTIALLY_RECEIVED",
    requestedQty: 1200,
    approvedQty: 1200,
    pendingQty: 360,
  },
  {
    id: "mr3",
    requestNo: "MR-24034",
    projectId: "3",
    project: "Solar Assembly Line",
    activityId: "5",
    activity: "Production Line Modeling",
    requestedBy: "Harish P",
    status: "SUBMITTED",
    requestedQty: 240,
    approvedQty: 0,
    pendingQty: 240,
  },
];

export const reportSnapshots: ReportSnapshot[] = [
  { month: "Jan", budget: 18, actual: 14, allocated: 16 },
  { month: "Feb", budget: 21, actual: 17, allocated: 18 },
  { month: "Mar", budget: 24, actual: 20, allocated: 21 },
  { month: "Apr", budget: 26, actual: 22, allocated: 23 },
  { month: "May", budget: 30, actual: 25, allocated: 27 },
  { month: "Jun", budget: 32, actual: 29, allocated: 30 },
];

export const milestonePulse = [
  { name: "On Track", value: 14 },
  { name: "Watchlist", value: 5 },
  { name: "Delayed", value: 3 },
];
